# Generated by Django 3.1.1 on 2020-09-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('age', models.IntegerField(default=0)),
                ('playerImage', models.CharField(max_length=300)),
                ('playerLink', models.CharField(max_length=800)),
                ('fromTeam', models.CharField(max_length=100)),
                ('fromTeamImage', models.CharField(max_length=800)),
                ('toTeam', models.CharField(max_length=100)),
                ('toTeamImage', models.CharField(max_length=800)),
                ('position', models.CharField(max_length=100)),
                ('fee', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
    ]
